# Generated by Django 3.1.2 on 2020-10-30 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20201030_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_for_one',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator('0.01')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator('1')]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator('1')]),
        ),
    ]
