# Generated by Django 3.1.2 on 2020-11-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_auto_20201106_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='request_status',
            field=models.CharField(default='Action required', max_length=120),
        ),
    ]
