# Generated by Django 3.1.2 on 2020-11-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_auto_20201113_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='declined_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.purchase'),
        ),
    ]
