# Generated by Django 3.1.2 on 2020-11-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_auto_20201113_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='declined_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop_app.purchase'),
        ),
        migrations.AlterField(
            model_name='return',
            name='request_status',
            field=models.CharField(default='Action required', max_length=120),
        ),
    ]
