# Generated by Django 3.1.2 on 2020-11-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_auto_20201115_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='New description'),
        ),
    ]
